// Code for visualizing ascii-encoded elevation data

#pragma once

#include "resource.h"
#include "framework.h"
#include <iostream>
#include <fstream>
#include <sstream>
#include <vector>
#include <algorithm>

// Path to .asc file, hard coded for now
#define TARGET_FILE "./files/L3324.asc"

using namespace std;

// Holds metadata about the map
class MapMetadata {
public:
	int mapwidth = 0;
	int mapheight = 0;
	int nodatavalue = 0;
	int mapsize = 0;

	void CalculateMapSize() { mapsize = mapwidth * mapheight; };
};

// Holds an array of RGB bytes
class MapRGBData {
public:
	unsigned char* rgbdata;
	void Initialize(int mapsize) { rgbdata = new unsigned char[mapsize * 3]; };
	~MapRGBData() { delete[] rgbdata; };
};

// Holds the necessary bitmap header
// Also holds a function for setting RGB bytes generated by the program into a bitmap
class BitmapData {
	int width, height;
	void* pMap;
	HBITMAP bitmapHandle;
	HDC hdc;

public:
	BITMAPINFOHEADER mapHeader;
	BITMAPINFO mapInfo;

	BitmapData(HDC thdc, HBITMAP thandle, void* tpMap, int twidth, int theight) {
		width = twidth;
		height = theight;
		pMap = tpMap;
		hdc = thdc;
		bitmapHandle = thandle;

		mapHeader = {
		   sizeof(BITMAPINFOHEADER),	//bV5Size
		   width,		//bV5Width
		   -height,		//bV5Height
		   1,			//bV5Planes
		   24,			//bV5BitCount
		   BI_RGB,		//bV5Compression
		   0,			//bV5SizeImage
		   0,			//bV5XPelsPerMeter
		   0,			//bV5YPelsPerMeter
		   0,			//bV5ClrUsed
		   0,			//bV5ClrImportant
		};

		mapInfo = {
			mapHeader
		};
	};

	int DIBtoDDB() {
		int dib = SetDIBits(hdc, bitmapHandle, 1, height, pMap, &mapInfo, DIB_PAL_COLORS);
		if (dib == 0) {
			::MessageBox(NULL, __T("Failed to set DIBits."), __T("Error"), MB_OK);
			return NULL;
		}
		else return dib;
	};
};

// Calculates RGB values based on provided elevation data, used by FileIntoRGB()
void CalculateRGBValues(vector<double>&, unsigned char*&, MapMetadata&);

// Main function for opening and handling the file
// open file -> tokenize + convert to float -> convert to RGB bytes
// Target file hardcoded (for now) see TARGET_FILE in KorkeusDEMO.h to change path/file
bool FileIntoRGB(MapRGBData&, MapMetadata&);